[Icon Theme]
Name=Meridian
Comment=Icon theme for Meridian OS
Inherits=Papirus-Dark,breeze,hicolor
Example=folder

Directories=apps/16,apps/22,apps/24,apps/32,apps/48,apps/64,apps/128,apps/256,apps/scalable,places/scalable,mimetypes/scalable,status/scalable,actions/scalable

[apps/16]
Size=16
Type=Fixed
Context=Applications

[apps/22]
Size=22
Type=Fixed
Context=Applications

[apps/24]
Size=24
Type=Fixed
Context=Applications

[apps/32]
Size=32
Type=Fixed
Context=Applications

[apps/48]
Size=48
Type=Fixed
Context=Applications

[apps/64]
Size=64
Type=Fixed
Context=Applications

[apps/128]
Size=128
Type=Fixed
Context=Applications

[apps/256]
Size=256
Type=Fixed
Context=Applications

[apps/scalable]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[places/scalable]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[mimetypes/scalable]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes

[status/scalable]
Size=22
MinSize=8
MaxSize=512
Type=Scalable
Context=Status

[actions/scalable]
Size=22
MinSize=8
MaxSize=512
Type=Scalable
Context=Actions
